env: development
acme_ca_server: 'https://127.0.0.1:8443/acme/acme/directory'
mysql_root_password: "{{ vault_mysql_root_password }}" # Define this variable in group_vars/development/vault.yml
web_user: vagrant
