- include_tasks:
    file: local_ca.yml
    apply:
      become: yes
  when:
    - env == 'development'
    - sites_using_acme_ssl | count

- name: Install certbot packages
  apt:
    name:
      - certbot
      - python3-certbot
    state: present

- import_tasks: nginx.yml

- name: Register with ACME CA server
  shell: |
    certbot register --agree-tos --no-eff-email --email {{ acme_ca_contact_emails | join(",") }} --server {{ acme_ca_server }}
  become: yes
  register: acme_registration
  failed_when:
    - acme_registration.rc != 0
    - '"There is an existing account" not in acme_registration.stderr'

- name: Install cronjob for certificate renewal
  cron:
    cron_file: acme-certificate-renewal
    name: ACME certificate renewal
    user: root
    job: certbot renew -q --deploy-hook "/usr/sbin/service nginx reload"
    day: "{{ ssl_renewal_cronjob_daysofmonth }}"
    hour: "4"
    minute: "30"
    state: present

- name: Generate SSL certificates
  include_tasks:
    file: "{{ site_ssl.acme.challenge.type }}.yml"
    apply:
      become: yes
  when: site_uses_acme
  with_dict: "{{ wordpress_sites }}"
  tags: [wordpress, wordpress-setup, wordpress-setup-nginx, nginx-includes]
